### ISSUE TITLE
MetaHeuristica - Algo Genetico:

### ISSUE THREAD

**Issue by OmarHernandez99** [CSProjectsAvatar/SimCopIA#7]
- Seleccion de Padres
- Generacion de Hijos

**Comment by OmarHernandez99** [comment]
Clau que paso con el test mio de getChilds? Pq fallo?

**Comment by ClauP99** [comment]
Falla porque al generar los random parents es igual a childs

**Comment by OmarHernandez99** [comment]
Fueron problemas por el Random, arreglado con Semilla de `Environment.Ticks`
