### ISSUE TITLE
MetaHeuristica - Algo Genetico:

### ISSUE THREAD

**Issue by OmarHernandez99** [CSProjectsAvatar/SimCopIA#8]
- Metodo Principal
- Sampler
- Tests Asociados

**Comment by MakeMake23** [comment]
@OmarHernandez99 voa cerrar esto y moverlo pa _done_. Cualkier cosa q c decida reabrirlo, es necesario moverlo pa otro proyecto, xq est proyecto es d la 1ra entrega.
